version: '3'
services:
  app:
    container_name: zoo_app
    restart: always
    build: ./
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: zoo_mongo
    image: mongo
    ports:
      - '27017:27017'